version: '3.8'
services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached      
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
